### ISSUE TITLE
Typing in either field in the dialog causes Sketch to crash.

### ISSUE THREAD

**Issue by jawngee** [abynim/UserFlows#1] opened 2015-05-20 01:43 UTC
Using both Sketch 3.3.1 or 3.3.2:

- Select elements to link for flow
- Run the plugin
- After the dialog appears, typing anything on the keyboard causes Sketch to crash

Note that even if I hit cancel, Sketch will crash on any keyboard input afterwards.  

I'm not sure if this is your plugin per se, or Sketch itself.  But I use other plugins with dialogs and don't have this issue at all.

**Comment by abynim** [comment] 2015-05-20 02:10
The plugin uses the new format that was introduced in Sketch 3.3. It will
not work in earlier versions. Please update Sketch to the latest version if
possible and let me know if the problem persists.

**Comment by jawngee** [comment] 2015-05-20 02:11
Sorry that was a typo when I entered the issue.

This is happening with the 3.3.1 and 3.3.2 (on my machine at least).

On Wed, May 20, 2015 at 9:10 AM, Aby Nimbalkar <notifications@github.com>
wrote:

> The plugin uses the new format that was introduced in Sketch 3.3. It will
> not work in earlier versions. Please update Sketch to the latest version if
> possible and let me know if the problem persists.
>
> On Wednesday, May 20, 2015, Jon Gilkison <notifications@github.com> wrote:
>
> > Using both Sketch 3.1.1 or 3.1.2:
> >
> > - Select elements to link for flow
> > - Run the plugin
> > - After the dialog appears, typing anything on the keyboard causes
> > Sketch to crash
> >
> > Note that even if I hit cancel, Sketch will crash on any keyboard input
> > afterwards.
> >
> > I'm not sure if this is your plugin per se, or Sketch itself. But I use
> > other plugins with dialogs and don't have this issue at all.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/abynim/UserFlows/issues/1>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abynim/UserFlows/issues/1#issuecomment-103724517>.
>



-- 

jon gilkison
principal, interfacelab
c: 347.645.0177
t: http://twitter.com/interfacelab
b: http://interfacelab.com/

**Comment by abynim** [comment] 2015-05-20 03:20
Does this happen with any Sketch file or with a specific Sketch file? Are you on Mavericks or Yosemite?
I can't reproduce this at my end so might need your help to debug. Can you send me the file you're having trouble with? aby [at] silverux [dot] com.

**Comment by jawngee** [comment] 2015-05-20 04:43
I've actually been able to reproduce.  It will crash if I have an extra
blank page with no artboards on it.  Will send a Sketch file to you.

On Wed, May 20, 2015 at 10:20 AM, Aby Nimbalkar <notifications@github.com>
wrote:

> Does this happen with any Sketch file or with a specific Sketch file? Are
> you on Mavericks or Yosemite?
> I can't reproduce this at my end so might need your help to debug. Can you
> send me the file you're having trouble with? aby [at] silverux [dot] com.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abynim/UserFlows/issues/1#issuecomment-103743097>.
>



-- 

jon gilkison
principal, interfacelab
c: 347.645.0177
t: http://twitter.com/interfacelab
b: http://interfacelab.com/

**Comment by abynim** [comment] 2015-05-20 04:46
Perfect. I could reproduce it. Will add a fix in a bit. Thanks!

**Comment by abynim** [comment] 2015-05-20 07:06
Pushed a fix for this. Thanks @jawngee for your help with debugging.

**Closed by abynim** 2015-05-20 07:06 UTC
